### ISSUE TITLE
Move from JSON config files to XML config files

### ISSUE THREAD

**Issue by oli-h** [swisspush/gateleen#108]
In Gateleen, we have routing rules, schedulers and delegates, all defined in JSON format - but to be honest: editing JSON files is a mess.

Most text editors around do not do no syntax highlighting (as the *.json file extension is missing for all those gateleen config files), no suggestion, no syntax validation - no help at all.

Having the config files in XML format would be more helpful - and is also easily parseable in Java. Gateleen could offer propper and well-known formatted XSD schema files (http://github.com/swisspush/..../*.xsd) and most IDE Editors arount (e.g. IntelliJ, Eclipse, XML-Spy etc.) will pick them up automatically and will give lot of help while working on those files.

**Comment by floriankammermann** [comment]
But we have now json schemas for the rules and intellij comes with a JSON Schema Plugin (https://www.jetbrains.com/help/idea/2016.3/json-schema.html). Then also our resource editor is based on json and validates the json in the editor against syntactical correctness. So where is the benefit of switching to xml.

**Comment by oli-h** [comment]
Benefits
- XML editors picks up XSD schema automatically as the schema location can (and should) be declared in the XML itself
- **We can add comments** - anywhere in the XML. And they normally have special syntax coloring in XML editors.
- Even IntelliJ is not smart enough to identify files like "rules" (Routing rules) as JSON
- You can have multi-line text nodes

**Comment by matthiasbaldi** [comment]
When one of the greatest benefits is coloring or commenting, we should use yaml instead of JSON and not XML. But in my opinion is JSON anyway better readable than the other two formats (with or without comments).
And an other important point is, as @floriankammermann said, the other tools around of the ressources are often on a (JSON friendly) Javascript (Schema)/ AngularJS stack.

But I'm with you about the editing and documenting of large JSON files, maybe we can split them or we have to search and other way to improve the "rule management".

**Comment by oli-h** [comment]
Meanwhile we have "doc" properties in most Gateleen config schemas (routing rules, schedulers, delegates, hooks etc...)- and we have JSON-schema files and usable IDE-Plugins for them.
So the advantage of XML shrinks. I close the issue.

Still: The idea to migrate to yaml is nice - at least we have comments there
