### ISSUE TITLE
Queued Requests are not logged with the x-queue Header

### ISSUE THREAD

**Issue by mcweba** [swisspush/gateleen#25]
The queued requests are not logged with the x-queue Header. This makes it impossible to identify them in the log files. 
Find a way to log the request before it is queued and the x-queue header gets removed (QueuingHandler, line 57)

**Solution**

1. In the QueuingHandler don't remove the x-queue header, but set an additional header eg. x-queue-inbound-processed="true"
2. In the QueuingHandler the method isQueued will check additionally if the the x-queue-inbound-processed is **not** set

**Comment by lbovet** [comment]
This is quite a change in the semantics introducing incompatibility. This will break some of our use cases because we forward queued requests to other queues. We will have to remove this new header.
I would prefer to let this be done in client code (this is a logging specific feature), clients code can just make a copy of the x-queue header into a custom header for logging purpose.
Headers are part of the gateleen API. If their semantic changes, the API changes.

**Comment by mcweba** [comment]
As discussed with @lbovet, we don't add this functionality to gateleen itself. To log this header anyway, an additional header has to be added to the request which then will be logged. See example code below:

```java
private void addQueueLogHeader(HttpServerRequest request){
	String queue = request.getHeader("x-queue");
	if(queue != null){
		request.headers().set("x-queue-log", queue);
	}
}
```
This issue will be closed without modification.
